#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="$(hab pkg path billmeyer/apache-tomcat)/tc"

echo "Executing Tomcat here: ${TOMCAT_HOME}/bin/catalina.sh"
exec ${TOMCAT_HOME}/bin/catalina.sh run